// <auto-generated />
namespace Its.Systems.HR.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UpdatedonenameofsessioncolumntoIsOpenForExpressionOfInterest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedonenameofsessioncolumntoIsOpenForExpressionOfInterest));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070851352_Updated one name of sessioncolumn to IsOpenForExpressionOfInterest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
