//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Infrastructure.MappingViews;

[assembly: DbMappingViewCacheTypeAttribute(
    typeof(Its.Systems.HR.Infrastructure.HRContext),
    typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsb9e4692f470ea12d70d8c7a4930fadc61531354589f80c84123b4c10236fb75e))]

namespace Edm_EntityMappingGeneratedViews
{
    using System;
    using System.CodeDom.Compiler;
    using System.Data.Entity.Core.Metadata.Edm;

    /// <summary>
    /// Implements a mapping view cache.
    /// </summary>
    [GeneratedCode("Entity Framework Power Tools", "0.9.0.0")]
    internal sealed class ViewsForBaseEntitySetsb9e4692f470ea12d70d8c7a4930fadc61531354589f80c84123b4c10236fb75e : DbMappingViewCache
    {
        /// <summary>
        /// Gets a hash value computed over the mapping closure.
        /// </summary>
        public override string MappingHashValue
        {
            get { return "b9e4692f470ea12d70d8c7a4930fadc61531354589f80c84123b4c10236fb75e"; }
        }

        /// <summary>
        /// Gets a view corresponding to the specified extent.
        /// </summary>
        /// <param name="extent">The extent.</param>
        /// <returns>The mapping view, or null if the extent is not associated with a mapping view.</returns>
        public override DbMappingView GetView(EntitySetBase extent)
        {
            if (extent == null)
            {
                throw new ArgumentNullException("extent");
            }

            var extentName = extent.EntityContainer.Name + "." + extent.Name;

            if (extentName == "CodeFirstDatabase.Activity")
            {
                return GetView0();
            }

            if (extentName == "CodeFirstDatabase.Session")
            {
                return GetView1();
            }

            if (extentName == "CodeFirstDatabase.Participant")
            {
                return GetView2();
            }

            if (extentName == "CodeFirstDatabase.SessionParticipant")
            {
                return GetView3();
            }

            if (extentName == "CodeFirstDatabase.Location")
            {
                return GetView4();
            }

            if (extentName == "CodeFirstDatabase.SessionTag")
            {
                return GetView5();
            }

            if (extentName == "CodeFirstDatabase.Tag")
            {
                return GetView6();
            }

            if (extentName == "HRContext.Activities")
            {
                return GetView7();
            }

            if (extentName == "HRContext.Sessions")
            {
                return GetView8();
            }

            if (extentName == "HRContext.Participants")
            {
                return GetView9();
            }

            if (extentName == "HRContext.SessionParticipants")
            {
                return GetView10();
            }

            if (extentName == "HRContext.Locations")
            {
                return GetView11();
            }

            if (extentName == "HRContext.SessionTags")
            {
                return GetView12();
            }

            if (extentName == "HRContext.Tags")
            {
                return GetView13();
            }

            return null;
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Activity.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView0()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Activity
        [CodeFirstDatabaseSchema.Activity](T1.Activity_Id, T1.Activity_Name)
    FROM (
        SELECT 
            T.Id AS Activity_Id, 
            T.Name AS Activity_Name, 
            True AS _from0
        FROM HRContext.Activities AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Session.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView1()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Session
        [CodeFirstDatabaseSchema.Session](T1.Session_Id, T1.Session_Name, T1.Session_StartDate, T1.Session_EndDate, T1.Session_Comments, T1.Session_Evaluation, T1.Session_LocationId, T1.Session_HrPersonId, T1.Session_ActivityId)
    FROM (
        SELECT 
            T.Id AS Session_Id, 
            T.Name AS Session_Name, 
            T.StartDate AS Session_StartDate, 
            T.EndDate AS Session_EndDate, 
            T.Comments AS Session_Comments, 
            T.Evaluation AS Session_Evaluation, 
            T.LocationId AS Session_LocationId, 
            T.HrPersonId AS Session_HrPersonId, 
            T.ActivityId AS Session_ActivityId, 
            True AS _from0
        FROM HRContext.Sessions AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Participant.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView2()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Participant
        [CodeFirstDatabaseSchema.Participant](T1.Participant_Id, T1.Participant_CasId, T1.Participant_IsHrPerson, T1.Participant_IsActive, T1.Participant_IsSuperAdmin, T1.Participant_FirstName, T1.Participant_LastName, T1.Participant_Comments, T1.Participant_Wishes)
    FROM (
        SELECT 
            T.Id AS Participant_Id, 
            T.CasId AS Participant_CasId, 
            T.IsHrPerson AS Participant_IsHrPerson, 
            T.IsActive AS Participant_IsActive, 
            T.IsSuperAdmin AS Participant_IsSuperAdmin, 
            T.FirstName AS Participant_FirstName, 
            T.LastName AS Participant_LastName, 
            T.Comments AS Participant_Comments, 
            T.Wishes AS Participant_Wishes, 
            True AS _from0
        FROM HRContext.Participants AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SessionParticipant.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView3()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SessionParticipant
        [CodeFirstDatabaseSchema.SessionParticipant](T1.SessionParticipant_SessionId, T1.SessionParticipant_ParticipantId, T1.SessionParticipant_Rating, T1.SessionParticipant_Comments)
    FROM (
        SELECT 
            T.SessionId AS SessionParticipant_SessionId, 
            T.ParticipantId AS SessionParticipant_ParticipantId, 
            T.Rating AS SessionParticipant_Rating, 
            T.Comments AS SessionParticipant_Comments, 
            True AS _from0
        FROM HRContext.SessionParticipants AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Location.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView4()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Location
        [CodeFirstDatabaseSchema.Location](T1.Location_Id, T1.Location_Name, T1.Location_Address)
    FROM (
        SELECT 
            T.Id AS Location_Id, 
            T.Name AS Location_Name, 
            T.Address AS Location_Address, 
            True AS _from0
        FROM HRContext.Locations AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.SessionTag.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView5()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SessionTag
        [CodeFirstDatabaseSchema.SessionTag](T1.SessionTag_SessionId, T1.SessionTag_TagId)
    FROM (
        SELECT 
            T.SessionId AS SessionTag_SessionId, 
            T.TagId AS SessionTag_TagId, 
            True AS _from0
        FROM HRContext.SessionTags AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for CodeFirstDatabase.Tag.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView6()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Tag
        [CodeFirstDatabaseSchema.Tag](T1.Tag_Id, T1.Tag_Name)
    FROM (
        SELECT 
            T.Id AS Tag_Id, 
            T.Name AS Tag_Name, 
            True AS _from0
        FROM HRContext.Tags AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.Activities.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView7()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Activities
        [Its.Systems.HR.Infrastructure.Activity](T1.Activity_Id, T1.Activity_Name)
    FROM (
        SELECT 
            T.Id AS Activity_Id, 
            T.Name AS Activity_Name, 
            True AS _from0
        FROM CodeFirstDatabase.Activity AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.Sessions.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView8()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Sessions
        [Its.Systems.HR.Infrastructure.Session](T1.Session_Id, T1.Session_Name, T1.Session_StartDate, T1.Session_EndDate, T1.Session_Comments, T1.Session_Evaluation, T1.Session_LocationId, T1.Session_HrPersonId, T1.Session_ActivityId)
    FROM (
        SELECT 
            T.Id AS Session_Id, 
            T.Name AS Session_Name, 
            T.StartDate AS Session_StartDate, 
            T.EndDate AS Session_EndDate, 
            T.Comments AS Session_Comments, 
            T.Evaluation AS Session_Evaluation, 
            T.LocationId AS Session_LocationId, 
            T.HrPersonId AS Session_HrPersonId, 
            T.ActivityId AS Session_ActivityId, 
            True AS _from0
        FROM CodeFirstDatabase.Session AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.Participants.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView9()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Participants
        [Its.Systems.HR.Infrastructure.Participant](T1.Participant_Id, T1.Participant_CasId, T1.Participant_IsHrPerson, T1.Participant_IsActive, T1.Participant_IsSuperAdmin, T1.Participant_FirstName, T1.Participant_LastName, T1.Participant_Comments, T1.Participant_Wishes)
    FROM (
        SELECT 
            T.Id AS Participant_Id, 
            T.CasId AS Participant_CasId, 
            T.IsHrPerson AS Participant_IsHrPerson, 
            T.IsActive AS Participant_IsActive, 
            T.IsSuperAdmin AS Participant_IsSuperAdmin, 
            T.FirstName AS Participant_FirstName, 
            T.LastName AS Participant_LastName, 
            T.Comments AS Participant_Comments, 
            T.Wishes AS Participant_Wishes, 
            True AS _from0
        FROM CodeFirstDatabase.Participant AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.SessionParticipants.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView10()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SessionParticipants
        [Its.Systems.HR.Infrastructure.SessionParticipant](T1.SessionParticipant_SessionId, T1.SessionParticipant_ParticipantId, T1.SessionParticipant_Rating, T1.SessionParticipant_Comments)
    FROM (
        SELECT 
            T.SessionId AS SessionParticipant_SessionId, 
            T.ParticipantId AS SessionParticipant_ParticipantId, 
            T.Rating AS SessionParticipant_Rating, 
            T.Comments AS SessionParticipant_Comments, 
            True AS _from0
        FROM CodeFirstDatabase.SessionParticipant AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.Locations.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView11()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Locations
        [Its.Systems.HR.Infrastructure.Location](T1.Location_Id, T1.Location_Name, T1.Location_Address)
    FROM (
        SELECT 
            T.Id AS Location_Id, 
            T.Name AS Location_Name, 
            T.Address AS Location_Address, 
            True AS _from0
        FROM CodeFirstDatabase.Location AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.SessionTags.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView12()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing SessionTags
        [Its.Systems.HR.Infrastructure.SessionTag](T1.SessionTag_SessionId, T1.SessionTag_TagId)
    FROM (
        SELECT 
            T.SessionId AS SessionTag_SessionId, 
            T.TagId AS SessionTag_TagId, 
            True AS _from0
        FROM CodeFirstDatabase.SessionTag AS T
    ) AS T1");
        }

        /// <summary>
        /// Gets the view for HRContext.Tags.
        /// </summary>
        /// <returns>The mapping view.</returns>
        private static DbMappingView GetView13()
        {
            return new DbMappingView(@"
    SELECT VALUE -- Constructing Tags
        [Its.Systems.HR.Infrastructure.Tag](T1.Tag_Id, T1.Tag_Name)
    FROM (
        SELECT 
            T.Id AS Tag_Id, 
            T.Name AS Tag_Name, 
            True AS _from0
        FROM CodeFirstDatabase.Tag AS T
    ) AS T1");
        }
    }
}
